version: "3.8"


services:
  delivery-service:
    build:
      context: "../"
      dockerfile: "./docker/dev.Dockerfile"
    restart: on-failure
    environment:
       - BOT_TOKEN
       - DB_PASSWORD
       - BOT_URL
       - ADMIN_URL
       - GROUP_CHAT_ID=0
       - DB_URL
       - ENV

    volumes:
      - ../:/app
    ports:
      - "9000:9000"
